/* scheme/write_sob_symbol.asm
 * Take a pointer to a Scheme symbol object, and
 * prints (to stdout) the character representation
 * of that object.
 *
 * WRITE_SOB_SYMBOL_STRING - is the same like WRITE_SOB_STRING but without the " in the start and in the end
 *
 */
 WRITE_SOB_SYMBOL:
   PUSH(FP);
   MOV(FP, SP);
   MOV(R0, FPARG(0));
   MOV(R0, INDD(R0, 1));
   PUSH(R0);
   CALL(WRITE_SOB_SYMBOL_STRING);
   DROP(1);
   POP(FP);
   RETURN;

 WRITE_SOB_SYMBOL_STRING:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);
  PUSH(R3);
  MOV(R0, FPARG(0));
  MOV(R1, INDD(R0, 1));
  MOV(R2, R0);
  ADD(R2, IMM(2));
 L_WSS_LOOP_SYMBOL_STRING:
  CMP(R1, IMM(0));
  JUMP_EQ(L_WSS_EXIT_SYMBOL_STRING);
  CMP(IND(R2), '\n');
  JUMP_EQ(L_WSS_NEWLINE_SYMBOL_STRING);
  CMP(IND(R2), '\t');
  JUMP_EQ(L_WSS_TAB_SYMBOL_STRING);
  CMP(IND(R2), '\f');
  JUMP_EQ(L_WSS_PAGE_SYMBOL_STRING);
  CMP(IND(R2), '\r');
  JUMP_EQ(L_WSS_RETURN_SYMBOL_STRING);
  CMP(IND(R2), '\\');
  JUMP_EQ(L_WSS_BACKSLASH_SYMBOL_STRING);
  CMP(IND(R2), '\"');
  JUMP_EQ(L_WSS_DQUOTE_SYMBOL_STRING);
  CMP(IND(R2), ' ');
  JUMP_LT(L_WSS_OCT_CHAR_SYMBOL_STRING);
  PUSH(IND(R2));
  CALL(PUTCHAR);
  DROP(1);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_DQUOTE_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('\"'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_BACKSLASH_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_RETURN_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('r'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_PAGE_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('f'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_TAB_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('t'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_NEWLINE_SYMBOL_STRING:
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  PUSH(IMM('n'));
  CALL(PUTCHAR);
  DROP(2);
  JUMP(L_WSS_LOOP_CONT_SYMBOL_STRING);
 L_WSS_OCT_CHAR_SYMBOL_STRING:
  MOV(R0, IND(R2));
  MOV(R3, R0);
  REM(R3, IMM(8));
  PUSH(R3);
  DIV(R0, IMM(8));
  MOV(R3, R0);
  REM(R3, IMM(8));
  PUSH(R3);
  DIV(R0, IMM(8));
  REM(R0, IMM(8));
  PUSH(R0);
  PUSH(IMM('\\'));
  CALL(PUTCHAR);
  DROP(1);
  CALL(WRITE_INTEGER);
  DROP(1);
  CALL(WRITE_INTEGER);
  DROP(1);
  CALL(WRITE_INTEGER);
  DROP(1);
 L_WSS_LOOP_CONT_SYMBOL_STRING:
  INCR(R2);
  DECR(R1);
  JUMP(L_WSS_LOOP_SYMBOL_STRING);
 L_WSS_EXIT_SYMBOL_STRING:
  POP(R3);
  POP(R2);
  POP(R1);
  POP(FP);
  RETURN;

