
LERROR_NOT_CLOSURE:
  //printf("LERROR_NOT_CLOSURE", R0);
  //SHOW("LERROR_NOT_CLOSURE", R0);
  JUMP(LERROR_HANDLE);

LERROR_NUM_OF_PARAMS_NO_MATCH:
  //SHOW("LERROR_NUM_OF_PARAMS_NO_MATCH", R0);
  JUMP(LERROR_HANDLE);

LERROR_TYPE_MISMATCH:
  //SHOW("LERROR_TYPE_MISMATCH", R0);
  JUMP(LERROR_HANDLE);

LERROR_INDEX_OUT_OF_RANGE:
  //SHOW("LERROR_INDEX_OUT_OF_RANGE", R0);
  JUMP(LERROR_HANDLE);

LERROR_DIVIDE_BY_ZERO:
  //SHOW("LERROR_DIVIDE_BY_ZERO",R0);
  JUMP(LERROR_HANDLE);

LERROR_HANDLE:
  PUSH(IMM(8));
  CALL(WRITE_SOB);
  DROP(1);
  CALL(NEWLINE);
  JUMP(END_PROG);