/* Eq? function */

L_EQ:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);

  CMP(FPARG(1), 2);
  JUMP_NE(LERROR_NUM_OF_PARAMS_NO_MATCH);

  MOV(R1, FPARG(2));
  MOV(R2, FPARG(3));
  CMP(IND(R1), IND(R2));   // Compare the types of object
  JUMP_NE(L_EQ_FALSE);

  PUSH(R1);
  CALL(IS_SOB_INTEGER);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(l_EQ_COMPARE_VALUES);

  PUSH(R1);
  CALL(IS_SOB_CHAR);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(l_EQ_COMPARE_VALUES);

  PUSH(R1);
  CALL(IS_SOB_SYMBOL);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(l_EQ_COMPARE_VALUES);

  PUSH(R1);
  CALL(IS_SOB_FRACTION);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(l_EQ_COMPARE_LONG_VALUES);

L_EQ_COMPARE_ADDRESS:
  CMP(R1, R2);
  JUMP_NE(L_EQ_FALSE);
  JUMP(L_EQ_TRUE);

l_EQ_COMPARE_LONG_VALUES:
  CMP(INDD(R1, 2), INDD(R2, 2));
  JUMP_NE(L_EQ_FALSE);

l_EQ_COMPARE_VALUES:
  CMP(INDD(R1, 1), INDD(R2, 1));
  JUMP_EQ(L_EQ_TRUE);

L_EQ_FALSE:
  MOV(R0, IMM(6));
  JUMP(L_EQ_EXIT);
L_EQ_TRUE:
  MOV(R0, IMM(8));

L_EQ_EXIT:

  POP(R2);
  POP(R1);
  POP(FP);
  RETURN;