/* number? function */

L_NUMBER:
  PUSH(FP);
  MOV(FP, SP);

  CMP(FPARG(1), 1);
  JUMP_NE(LERROR_NUM_OF_PARAMS_NO_MATCH);

  PUSH(FPARG(2));
  CALL(IS_SOB_INTEGER);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(L_NUMBER_TRUE);

  PUSH(FPARG(2));
  CALL(IS_SOB_FRACTION);
  DROP(1);
  CMP(R0, 1);
  JUMP_EQ(L_NUMBER_TRUE);

  MOV(R0, IMM(6));
  JUMP(L_NUMBER_EXIT);

L_NUMBER_TRUE:
  MOV(R0, IMM(8));

L_NUMBER_EXIT:
  POP(FP);
  RETURN;