/* string-ref function */

L_STRINGREF:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(R1);
  PUSH(R2);

  CMP(FPARG(1), 2);
  JUMP_NE(LERROR_NUM_OF_PARAMS_NO_MATCH);

  MOV(R1,FPARG(2));
  PUSH(R1);
  CALL(IS_SOB_STRING);
  DROP(1);
  CMP(R0, 1);
  JUMP_NE(LERROR_TYPE_MISMATCH);

  MOV(R2,FPARG(3));
  PUSH(R2);
  CALL(IS_SOB_INTEGER);
  DROP(1);
  CMP(R0, 1);
  JUMP_NE(LERROR_TYPE_MISMATCH);

  MOV(R2, INDD(R2,1));

  INCR(R2);
  CMP(R2, INDD(R1,1));
  JUMP_GT(LERROR_INDEX_OUT_OF_RANGE);

  INCR(R2);
  PUSH(INDD(R1,R2));
  CALL(MAKE_SOB_CHAR);
  DROP(1);

  POP(R2);
  POP(R1);
  POP(FP);
  RETURN;